stages:
  - build
  - deploy

latex:
  stage: build
  image: listx/texlive:2020
  script:
    - latexmk -e '$max_repeat=10' -pdf phd.tex

  artifacts:
    paths:
      - "phd.pdf"
    expire_in: 1 day # Latest one is kept anyway

  tags:
    - small

pages:
  stage: deploy
  script:
    - mkdir public
    - cp phd.pdf public
    - cp www/index.html public

  artifacts:
    paths:
      - public
    expire_in: 1 day # Same as above

  tags:
    - small
