build:
  image: listx/texlive:2020
  script:
    - latexmk -pdf

  artifacts:
    paths:
      - "phd.pdf"

  tags:
    - small

pages:
  script:
    - mkdir public
    - cp phd.pdf public

  artifacts:
    paths:
      - public
