stages:
  - build
  - deploy

latex:
  stage: build
  image: listx/texlive:2020
  script:
    - latexmk -pdf

  artifacts:
    paths:
      - "phd.pdf"

  tags:
    - small

pages:
  stage: deploy
  script:
    - mkdir public
    - cp phd.pdf public
    - cp www/index.html public

  artifacts:
    paths:
      - public

  tags:
    - small
